//! Code mode: give the model an API instead of a tool list.
//!
//! The premise, from Cloudflare's work and Anthropic's programmatic tool calling: models have seen
//! an enormous amount of real code and comparatively little tool-calling, which is mostly synthetic.
//! Handing a model a typed API and one `run_code` tool plays to that, and it collapses a chain of
//! round trips into a single script whose intermediate results never enter the context window.
//!
//! # What this module does, and what it deliberately does not
//!
//! It generates the **typed API surface** and models the **capability bindings**, and it decides
//! whether to delegate to a provider that can already do this. It does not embed a JavaScript
//! engine in the default build. Two reasons, both worth stating rather than hiding:
//!
//! * The generated surface is valuable on its own. It is emitted **even when code mode is off**,
//!   because it doubles as the description corpus that tool search indexes.
//! * Anthropic's programmatic tool calling runs the script on their side, so for that provider the
//!   right implementation is delegation, not a second sandbox.
//!
//! An embedded engine is a feature, not a default, and `notes/PROGRESS.md` records where that
//! stands. Shipping a default that pulls a JS runtime into every build of a Rust agent framework is
//! a cost every user pays for a feature most will delegate.

use frey_core::provider_caps::ProviderCapabilities;
use frey_core::tool_def::ToolDefinition;
use serde_json::Value;

/// How code mode should be provided for a given provider.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Strategy {
    /// The provider runs the script itself. Tools are marked so it knows which may be called from
    /// code, and intermediate results never reach the context window.
    Delegate,
    /// The provider cannot, so Frey would run the script locally.
    Local,
    /// Code mode is off; tools are presented normally.
    Off,
}

/// Decide how to provide code mode.
///
/// Delegation wins whenever it is available: the provider's own sandbox already exists, is already
/// audited, and keeps intermediate results off the wire entirely.
#[must_use]
pub fn strategy_for(caps: &ProviderCapabilities, enabled: bool) -> Strategy {
    if !enabled {
        Strategy::Off
    } else if caps.programmatic_tool_calling {
        Strategy::Delegate
    } else {
        Strategy::Local
    }
}

/// A generated TypeScript declaration for one tool.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Declaration {
    /// The function name as it appears in the API.
    pub name: String,
    /// The full declaration, including its doc comment.
    pub text: String,
}

/// Generate a typed API surface for a catalog.
///
/// TypeScript because it is what models have seen most of, and because a declaration file carries
/// the argument names and descriptions in a shape a model reads fluently — which is also why this
/// doubles as a search corpus.
#[must_use]
pub fn generate_api<'a>(tools: impl IntoIterator<Item = &'a ToolDefinition>) -> String {
    let declarations: Vec<Declaration> = tools.into_iter().map(declare).collect();
    let mut out = String::from(
        "// Generated by Frey. Each function calls a tool; results are ordinary values.\n\
         // Print what you want the model to see; everything else stays out of the context window.\n\n",
    );
    for declaration in declarations {
        out.push_str(&declaration.text);
        out.push_str("\n\n");
    }
    out
}

/// Generate the declaration for one tool.
#[must_use]
pub fn declare(tool: &ToolDefinition) -> Declaration {
    let name = tool.name.as_str().to_string();
    let mut text = String::new();

    text.push_str("/**\n");
    for line in wrap(&tool.description, 88) {
        text.push_str(" * ");
        text.push_str(&line);
        text.push('\n');
    }
    for (property, description) in documented_properties(tool.input_schema.as_value()) {
        text.push_str(&format!(" * @param {property} {description}\n"));
    }
    text.push_str(" */\n");

    text.push_str(&format!("declare function {name}(args: {{\n"));
    for (property, ty, required) in properties(tool.input_schema.as_value()) {
        let optional = if required { "" } else { "?" };
        text.push_str(&format!("  {property}{optional}: {ty};\n"));
    }
    text.push_str("}): Promise<string>;");

    Declaration { name, text }
}

fn properties(schema: &Value) -> Vec<(String, &'static str, bool)> {
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|props| {
            props
                .iter()
                .map(|(name, spec)| {
                    (name.clone(), typescript_type(spec), required.contains(&name.as_str()))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn documented_properties(schema: &Value) -> Vec<(String, String)> {
    schema
        .get("properties")
        .and_then(Value::as_object)
        .map(|props| {
            props
                .iter()
                .filter_map(|(name, spec)| {
                    spec.get("description")
                        .and_then(Value::as_str)
                        .filter(|d| !d.is_empty())
                        .map(|d| (name.clone(), d.to_string()))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn typescript_type(spec: &Value) -> &'static str {
    // JSON Schema allows a type to be absent or a union; anything not clearly scalar becomes
    // `unknown` rather than a guess, because a wrong type in a declaration teaches the model to
    // write code that fails.
    match spec.get("type").and_then(Value::as_str) {
        Some("string") => "string",
        Some("integer" | "number") => "number",
        Some("boolean") => "boolean",
        Some("array") => "unknown[]",
        Some("object") => "Record<string, unknown>",
        _ => "unknown",
    }
}

fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut current = String::new();
    for word in text.split_whitespace() {
        if !current.is_empty() && current.len() + word.len() + 1 > width {
            lines.push(std::mem::take(&mut current));
        }
        if !current.is_empty() {
            current.push(' ');
        }
        current.push_str(word);
    }
    if !current.is_empty() {
        lines.push(current);
    }
    if lines.is_empty() { vec![String::new()] } else { lines }
}

/// A capability handed to a script.
///
/// The critical property, taken from Cloudflare's binding model: a binding is a **handle, not a
/// credential**. Every call on it goes to the supervisor, which holds the token. A script cannot
/// leak a key it never had, which removes an entire class of failure rather than mitigating it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Binding {
    /// The name the script calls.
    pub name: String,
    /// Which tool it resolves to.
    pub tool: String,
}

/// Build the bindings a script may use.
///
/// Only tools whose caller policy permits code may be bound. Frey enforces that here as well as in
/// the tool layer, because the provider's own equivalent is documented as guidance to the model
/// rather than a boundary.
#[must_use]
pub fn bindings<'a>(tools: impl IntoIterator<Item = &'a ToolDefinition>) -> Vec<Binding> {
    tools
        .into_iter()
        .filter(|t| t.caller.allows_code())
        .map(|t| Binding { name: t.name.to_string(), tool: t.name.to_string() })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::profiles;
    use frey_core::tool_def::CallerPolicy;
    use frey_core::tool_def::JsonSchema;

    fn tool() -> ToolDefinition {
        let mut def = ToolDefinition::new(
            "db_query",
            "Run a read-only SQL statement against the analytics database and return rows as JSON",
            JsonSchema::new(serde_json::json!({
                "type": "object",
                "properties": {
                    "sql": {"type": "string", "description": "The statement, in Postgres dialect."},
                    "limit": {"type": "integer", "description": "Maximum rows to return."},
                    "explain": {"type": "boolean"}
                },
                "required": ["sql"]
            }))
            .unwrap(),
        );
        def.caller = CallerPolicy::CodeOnly;
        def
    }

    #[test]
    fn a_provider_that_can_run_the_script_gets_to() {
        // Its sandbox already exists and is already audited, and intermediate results never leave
        // its side at all.
        assert_eq!(strategy_for(&profiles::opus5(), true), Strategy::Delegate);
        assert_eq!(strategy_for(&profiles::openai(), true), Strategy::Local);
        assert_eq!(strategy_for(&profiles::opus5(), false), Strategy::Off);
    }

    #[test]
    fn the_declaration_carries_the_argument_descriptions() {
        // Which is why this surface doubles as the search corpus: it holds exactly the four fields
        // a tool search indexes.
        let text = declare(&tool()).text;
        assert!(text.contains("Postgres dialect"), "{text}");
        assert!(text.contains("@param sql"), "{text}");
        assert!(text.contains("db_query"), "{text}");
    }

    #[test]
    fn optional_arguments_are_marked_optional() {
        let text = declare(&tool()).text;
        assert!(text.contains("sql: string;"), "required: {text}");
        assert!(text.contains("limit?: number;"), "optional: {text}");
        assert!(text.contains("explain?: boolean;"), "{text}");
    }

    #[test]
    fn an_unclear_type_becomes_unknown_rather_than_a_guess() {
        // A wrong type in a declaration teaches the model to write code that fails, which is worse
        // than a type it has to narrow itself.
        let vague = ToolDefinition::new(
            "thing",
            "Does a thing with a value of an unspecified shape",
            JsonSchema::new(serde_json::json!({
                "type": "object",
                "properties": {"value": {}}
            }))
            .unwrap(),
        );
        assert!(declare(&vague).text.contains("value?: unknown;"));
    }

    #[test]
    fn the_api_is_generated_even_when_code_mode_is_off() {
        // It doubles as the description corpus for search, so it is worth generating regardless.
        let api = generate_api([&tool()]);
        assert!(api.contains("declare function db_query"));
        assert!(api.contains("Postgres dialect"));
    }

    #[test]
    fn only_code_callable_tools_are_bound() {
        // Enforced here as well as in the tool layer, because the provider's own equivalent is
        // documented as guidance to the model rather than a boundary.
        let mut direct = tool();
        direct.name = frey_core::ids::ToolName::new("fs_read");
        direct.caller = CallerPolicy::Direct;

        let bound = bindings([&tool(), &direct]);
        assert_eq!(bound.len(), 1);
        assert_eq!(bound[0].name, "db_query");
    }

    #[test]
    fn a_binding_names_a_tool_and_never_a_credential() {
        // The whole security argument for code mode: a script cannot leak a key it never had.
        let bound = bindings([&tool()]);
        let rendered = format!("{bound:?}");
        assert!(rendered.contains("db_query"));
        assert!(!rendered.contains("key") && !rendered.contains("token"), "{rendered}");
    }

    #[test]
    fn long_descriptions_wrap_rather_than_running_off() {
        let lines = wrap(&"word ".repeat(40), 40);
        assert!(lines.len() > 1);
        assert!(lines.iter().all(|l| l.len() <= 40));
    }

    #[test]
    fn a_tool_with_no_arguments_still_declares_cleanly() {
        let bare = ToolDefinition::new(
            "ping",
            "Check that the service is reachable and return its version",
            JsonSchema::empty_object(),
        );
        let text = declare(&bare).text;
        assert!(text.contains("declare function ping(args: {"), "{text}");
        assert!(text.contains("}): Promise<string>;"), "{text}");
    }
}
